version: "3.7"

services:

    rabbitmq:
        build: ./rabbitmq
        hostname: localhost
        container_name: rabbitmq
        restart: always
        ports:
            - "15672:15672"
            - "5672:5672"
            - "1883:1883"
        volumes:
            - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config


    uav_simulation:
        image: levakuz/uav_interface:0.15
        hostname: localhost
        restart: always
        command: python3 src/Simulation.py
        depends_on:
            - rabbitmq

    uav_type_rpc:
        image: levakuz/uav_interface:0.15
        hostname: localhost
        restart: always
        command: python3 src/uav_type_rpc.py
        depends_on:
            - rabbitmq

    uav_rpc_simulation:
        image: levakuz/uav_interface:0.15
        hostname: localhost
        restart: always
        command: python3 src/uav_rpc_simulation.py
        depends_on:
            - rabbitmq

    uav_rpc:
          image: levakuz/uav_interface:0.15
          hostname: localhost
          restart: always
          command: python3 src/uav_rpc.py
          depends_on:
            - rabbitmq

    uav_role_rpc:
          image: levakuz/uav_interface:0.15
          hostname: localhost
          restart: always
          command: python3 src/uav_role_rpc.py
          depends_on:
            - rabbitmq

    co_weapon_rpc:
          image: levakuz/uav_interface:0.15
          hostname: localhost
          restart: always
          command: python3 src/co_weapon_rpc.py
          depends_on:
            - rabbitmq

    co_type_rpc:
          image: levakuz/uav_interface:0.15
          hostname: localhost
          restart: always
          command: python3 src/co_type_rpc.py
          depends_on:
            - rabbitmq

    co_rpc:
          image: levakuz/uav_interface:0.15
          hostname: localhost
          restart: always
          command: python3 src/co_rpc.py
          depends_on:
            - rabbitmq

    environment_simulation:
          image: levakuz/uav_interface:0.15
          hostname: localhost
          restart: always
          command: python3 src/environment_simulation.py
          depends_on:
            - rabbitmq

    environment_simulation_rpc:
          image: levakuz/uav_interface:0.15
          hostname: localhost
          restart: always
          command: python3 src/environment_simulation_rpc.py
          depends_on:
            - rabbitmq


    web-api:
        image: levakuz/uav_interface:0.15
        hostname: localhost
        restart: always
        command: python3 src/API_db.py
        ports:
            - "8001:8001"
        depends_on:
            - rabbitmq

    pg_db:
      image: postgres
      restart: always
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres
      volumes:
        - pg_project:/var/lib/postgresql/data
      ports:
        - ${POSTGRES_PORT:-5432}:5432
